setup_steps: &setup_steps
  - uses: actions/checkout@v5
  - uses: actions/setup-node@v5
    with:
      node-version-file: '.nvmrc'
      cache: 'npm'
  - run: npm ci

name: Code Quality

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - *setup_steps
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - *setup_steps
      - run: npm run build
